In [1]:
import os
import sys
import pandas as pd

sys.path.append(os.path.abspath('../scripts'))

from kworb import Kworb
from genius import Genius

In [2]:
kworb = Kworb()
df = kworb.spotify_daily_chart_totals('2026-04-08')
df

2026-04-09 00:12:55,295 [INFO]: Данные за 2026-04-08 число получены из кэша

,date,artist_name,track_title,days_on_chart,top_10_days,peak_position,peak_occurrence,peak_streams,total_streams
rank,,,,,,,,,
1,2026-04-08,The Weeknd,Blinding Lights,2317,446,1,82.0,"8,453,567","5,268,588,903"
2,2026-04-08,Ed Sheeran,Shape of You,2831,237,1,98.0,"9,878,194","4,248,356,513"
3,2026-04-08,Harry Styles,As It Was,1417,426,1,81.0,"16,103,849","4,227,606,484"
4,2026-04-08,Lewis Capaldi,Someone You Loved,2388,107,4,NaN,"3,974,554","3,902,396,693"
5,2026-04-08,The Neighbourhood,Sweater Weather,2136,,12,NaN,"3,342,205","3,883,463,849"
...,...,...,...,...,...,...,...,...,...
11746,2026-04-08,Wisin,Adrenalina,1,,188,NaN,"124,862","124,862"
11747,2026-04-08,Iggy Azalea,Work,1,,196,NaN,"120,954","120,954"
11748,2026-04-08,Orup,Främling,1,,199,NaN,"120,760","120,760"
11749,2026-04-08,Ed Sheeran,Nina,1,,199,NaN,"120,515","120,515"
11750,2026-04-08,Take That,These Days,1,,198,NaN,"115,382","115,382"

In [3]:
genius = Genius()
genius.search('Blinding Lights The Weeknd')
genius.song(5049949)
genius.artist(2358)
genius.artist_songs(2358)
genius.referents(5049949)
...

2026-04-09 00:12:58,558 [INFO]: Использован кэш для searches с идентификатором Blinding Lights The Weeknd за 2026-04-08T18:11:34.439981
2026-04-09 00:12:58,620 [INFO]: Использован кэш для songs с идентификатором 5049949 за 2026-04-08T18:11:38.071447
2026-04-09 00:12:58,680 [INFO]: Использован кэш для artists с идентификатором 2358 за 2026-04-08T18:11:38.941794
2026-04-09 00:12:58,720 [INFO]: Использован кэш для artist_songs с идентификатором 2358 за 2026-04-08T18:13:38.019592
2026-04-09 00:12:58,886 [INFO]: Использован кэш для referents с идентификатором 5049949 за 2026-04-08T18:13:39.005266

Ellipsis

In [4]:
df[df['track_title'] == 'Sommer']

,date,artist_name,track_title,days_on_chart,top_10_days,peak_position,peak_occurrence,peak_streams,total_streams
rank,,,,,,,,,
10045,2026-04-08,Bonez MC,Sommer,1,,176,NaN,"929,469","929,469"

In [5]:
for _, row in df[10000:].iterrows():
    genius.search(f"{row['track_title']} — {row['artist_name']}")

2026-04-09 00:13:00,338 [INFO]: Использован кэш для searches с идентификатором all I know — mgk за 2026-04-08T23:15:01.303744
2026-04-09 00:13:01,135 [INFO]: Использован кэш для searches с идентификатором Menace — PNL за 2026-04-08T23:15:01.930346
2026-04-09 00:13:01,347 [INFO]: Использован кэш для searches с идентификатором 7 Am Freestyle — Future за 2026-04-08T23:15:02.328192
2026-04-09 00:13:01,475 [INFO]: Использован кэш для searches с идентификатором SAME ENERGY — The Kid LAROI за 2026-04-08T23:15:02.889633
2026-04-09 00:13:01,590 [INFO]: Использован кэш для searches с идентификатором Salem's Interlude — Khalid за 2026-04-08T23:15:04.026847
2026-04-09 00:13:01,661 [INFO]: Использован кэш для searches с идентификатором Sunshine — Steve Lacy за 2026-04-08T23:15:04.819630
2026-04-09 00:13:01,727 [INFO]: Использован кэш для searches с идентификатором Bad Business — 21 Savage за 2026-04-08T23:15:05.391880
2026-04-09 00:13:01,810 [INFO]: Использован кэш для searches с идентификатором @ my worst — blackbear за 2026-04-08T23:15:05.972055
2026-04-09 00:13:01,963 [INFO]: Использован кэш для searches с идентификатором Performance — The xx за 2026-04-08T23:15:06.507628
2026-04-09 00:13:02,046 [INFO]: Использован кэш для searches с идентификатором It's A Raid — Ozzy Osbourne за 2026-04-08T23:15:07.237399
2026-04-09 00:13:02,213 [INFO]: Использован кэш для searches с идентификатором title track — mgk за 2026-04-08T23:15:08.152644
2026-04-09 00:13:02,279 [INFO]: Использован кэш для searches с идентификатором Watch Out — 2 Chainz за 2026-04-08T23:15:08.957058
2026-04-09 00:13:02,376 [INFO]: Использован кэш для searches с идентификатором Games — Ufo361 за 2026-04-08T23:15:09.569557
2026-04-09 00:13:02,442 [INFO]: Использован кэш для searches с идентификатором Alone — Doja Cat за 2026-04-08T23:15:10.674997
2026-04-09 00:13:03,001 [INFO]: Использован кэш для searches с идентификатором Wild Blue — John Mayer за 2026-04-08T23:15:11.233376
2026-04-09 00:13:03,460 [INFO]: Использован кэш для searches с идентификатором flooded — Gunna за 2026-04-08T23:15:11.794194
2026-04-09 00:13:03,901 [INFO]: Использован кэш для searches с идентификатором Zoulou tchaing — PNL за 2026-04-08T23:15:12.320505
2026-04-09 00:13:04,275 [INFO]: Использован кэш для searches с идентификатором The Feast and The Famine — Foo Fighters за 2026-04-08T23:15:13.758887
2026-04-09 00:13:04,426 [INFO]: Использован кэш для searches с идентификатором Wild At Heart — Lana Del Rey за 2026-04-08T23:15:16.451573
2026-04-09 00:13:04,550 [INFO]: Использован кэш для searches с идентификатором DAS RENNEN — RIN за 2026-04-08T23:15:17.990398
2026-04-09 00:13:04,726 [INFO]: Использован кэш для searches с идентификатором So Real — Polo G за 2026-04-08T23:15:20.508144
2026-04-09 00:13:04,800 [INFO]: Использован кэш для searches с идентификатором Crack — SCH за 2026-04-08T23:15:22.259516
2026-04-09 00:13:04,901 [INFO]: Использован кэш для searches с идентификатором HERE (For Christmas) — Lukas Graham за 2026-04-08T23:15:23.140443
2026-04-09 00:13:04,966 [INFO]: Использован кэш для searches с идентификатором Du propre — Orelsan за 2026-04-08T23:15:23.798865
2026-04-09 00:13:05,049 [INFO]: Использован кэш для searches с идентификатором DUBBI — Marracash за 2026-04-08T23:15:24.411821
2026-04-09 00:13:05,832 [INFO]: Использован кэш для searches с идентификатором Feel The Love — KIDS SEE GHOSTS за 2026-04-08T22:03:22.823404
2026-04-09 00:13:06,453 [INFO]: Использован кэш для searches с идентификатором MACHETE SATELLITE — BLOODY VINYL за 2026-04-08T23:15:25.400640
2026-04-09 00:13:06,512 [INFO]: Использован кэш для searches с идентификатором Formidable — Twenty One Pilots за 2026-04-08T23:15:26.306672
2026-04-09 00:13:06,610 [INFO]: Использован кэш для searches с идентификатором Higher Ground — Martin Garrix за 2026-04-08T23:15:27.026414
2026-04-09 00:13:06,829 [INFO]: Использован кэш для searches с идентификатором Is This Love ('09) — Eminem за 2026-04-08T23:15:27.701411
2026-04-09 00:13:06,924 [INFO]: Использован кэш для searches с идентификатором original me — YUNGBLUD за 2026-04-08T23:15:28.386849
2026-04-09 00:13:07,001 [INFO]: Использован кэш для searches с идентификатором u love u — blackbear за 2026-04-08T23:15:28.884944
2026-04-09 00:13:07,127 [INFO]: Использован кэш для searches с идентификатором Around the World — Daft Punk за 2026-04-08T23:15:29.453628
2026-04-09 00:13:07,222 [INFO]: Использован кэш для searches с идентификатором Wild Love — James Bay за 2026-04-08T23:15:30.103209
2026-04-09 00:13:07,279 [INFO]: Использован кэш для searches с идентификатором Baby Boy — Childish Gambino за 2026-04-08T23:15:31.519662
2026-04-09 00:13:07,326 [INFO]: Использован кэш для searches с идентификатором The Glorious Five — Logic за 2026-04-08T23:15:32.642082
2026-04-09 00:13:07,398 [INFO]: Использован кэш для searches с идентификатором Conan x Xenia — Haftbefehl за 2026-04-08T23:15:33.071058
2026-04-09 00:13:07,509 [INFO]: Использован кэш для searches с идентификатором more than life — mgk за 2026-04-08T23:15:33.916058
2026-04-09 00:13:07,784 [INFO]: Использован кэш для searches с идентификатором There You Are — ZAYN за 2026-04-08T23:15:34.525233
2026-04-09 00:13:07,908 [INFO]: Использован кэш для searches с идентификатором Realize — AC/DC за 2026-04-08T23:15:35.064650
2026-04-09 00:13:07,975 [INFO]: Использован кэш для searches с идентификатором Sal y Perrea - Remix — Sech за 2026-04-08T23:15:35.713813
2026-04-09 00:13:08,049 [INFO]: Использован кэш для searches с идентификатором Too Much — ZAYN за 2026-04-08T23:15:36.804529
2026-04-09 00:13:08,148 [INFO]: Использован кэш для searches с идентификатором Jag trodde änglarna fanns — Kamferdrops за 2026-04-08T23:15:37.264607
2026-04-09 00:13:08,257 [INFO]: Использован кэш для searches с идентификатором Wanna Know Remix — Dave за 2026-04-08T23:15:37.817999
2026-04-09 00:13:08,419 [INFO]: Использован кэш для searches с идентификатором Sommer — Bonez MC за 2026-04-08T23:15:39.120861
2026-04-09 00:13:08,494 [INFO]: Использован кэш для searches с идентификатором Love's Train — Bruno Mars за 2026-04-08T23:15:41.209732
2026-04-09 00:13:08,544 [INFO]: Использован кэш для searches с идентификатором Runnin' with the Devil - 2015 Remaster — Van Halen за 2026-04-08T23:15:41.576098
2026-04-09 00:13:08,604 [INFO]: Использован кэш для searches с идентификатором Dark But Just A Game — Lana Del Rey за 2026-04-08T23:15:42.603107
2026-04-09 00:13:08,678 [INFO]: Использован кэш для searches с идентификатором Cheum — Nekfeu за 2026-04-08T23:15:43.215967
2026-04-09 00:13:08,760 [INFO]: Использован кэш для searches с идентификатором Runnin' Down A Dream — Tom Petty за 2026-04-08T23:15:44.083330
2026-04-09 00:13:08,843 [INFO]: Использован кэш для searches с идентификатором No Time — KSI за 2026-04-08T23:15:44.767548
2026-04-09 00:13:08,893 [INFO]: Использован кэш для searches с идентификатором man i is — Logic за 2026-04-08T23:15:45.749697
2026-04-09 00:13:08,947 [INFO]: Использован кэш для searches с идентификатором Draft Day — Drake за 2026-04-08T23:15:46.583034
2026-04-09 00:13:08,993 [INFO]: Использован кэш для searches с идентификатором Kids Turned Out Fine — A$AP Rocky за 2026-04-08T23:15:47.287549
2026-04-09 00:13:09,043 [INFO]: Использован кэш для searches с идентификатором Negative Energy — Trippie Redd за 2026-04-08T23:15:48.281186
2026-04-09 00:13:09,134 [INFO]: Использован кэш для searches с идентификатором SEX — Rammstein за 2026-04-08T23:15:48.939044
2026-04-09 00:13:09,225 [INFO]: Использован кэш для searches с идентификатором BPM — Damso за 2026-04-08T23:15:49.589268
2026-04-09 00:13:09,500 [INFO]: Отправлен поисковый запрос: Crush A Lot — Lil Baby
2026-04-09 00:13:09,603 [DEBUG]: Starting new HTTPS connection (1): api.genius.com:443
2026-04-09 00:13:10,676 [DEBUG]: https://api.genius.com:443 "GET /search?q=Crush+A+Lot+%E2%80%94+Lil+Baby HTTP/1.1" 200 None
2026-04-09 00:13:10,801 [INFO]: Отправлен поисковый запрос: Rosenkrieg — Loredana
2026-04-09 00:13:11,214 [DEBUG]: https://api.genius.com:443 "GET /search?q=Rosenkrieg+%E2%80%94+Loredana HTTP/1.1" 200 None
2026-04-09 00:13:11,885 [INFO]: Отправлен поисковый запрос: Itty Bitty Piggy — Nicki Minaj
2026-04-09 00:13:12,243 [DEBUG]: https://api.genius.com:443 "GET /search?q=Itty+Bitty+Piggy+%E2%80%94+Nicki+Minaj HTTP/1.1" 200 None
2026-04-09 00:13:12,345 [INFO]: Отправлен поисковый запрос: 7empest — TOOL
2026-04-09 00:13:12,622 [DEBUG]: https://api.genius.com:443 "GET /search?q=7empest+%E2%80%94+TOOL HTTP/1.1" 200 None
2026-04-09 00:13:12,647 [INFO]: Отправлен поисковый запрос: Beauty In The Benz — Tory Lanez
2026-04-09 00:13:13,298 [DEBUG]: https://api.genius.com:443 "GET /search?q=Beauty+In+The+Benz+%E2%80%94+Tory+Lanez HTTP/1.1" 200 None
2026-04-09 00:13:13,403 [INFO]: Отправлен поисковый запрос: Provide — G-Eazy
2026-04-09 00:13:13,817 [DEBUG]: https://api.genius.com:443 "GET /search?q=Provide+%E2%80%94+G-Eazy HTTP/1.1" 200 None
2026-04-09 00:13:13,924 [INFO]: Отправлен поисковый запрос: MERCEDES — XoMusic
2026-04-09 00:13:14,182 [DEBUG]: https://api.genius.com:443 "GET /search?q=MERCEDES+%E2%80%94+XoMusic HTTP/1.1" 200 46
2026-04-09 00:13:14,209 [INFO]: Отправлен поисковый запрос: COSPLAYER — Marracash
2026-04-09 00:13:14,629 [DEBUG]: https://api.genius.com:443 "GET /search?q=COSPLAYER+%E2%80%94+Marracash HTTP/1.1" 200 None
2026-04-09 00:13:15,907 [INFO]: Отправлен поисковый запрос: For the Love of New York — Polo G
2026-04-09 00:13:16,465 [DEBUG]: https://api.genius.com:443 "GET /search?q=For+the+Love+of+New+York+%E2%80%94+Polo+G HTTP/1.1" 200 None
2026-04-09 00:13:19,214 [INFO]: Отправлен поисковый запрос: CHOPPA SHOOT THE LOUDEST — Lil Tecca
2026-04-09 00:13:19,689 [DEBUG]: https://api.genius.com:443 "GET /search?q=CHOPPA+SHOOT+THE+LOUDEST+%E2%80%94+Lil+Tecca HTTP/1.1" 200 None
2026-04-09 00:13:19,873 [INFO]: Отправлен поисковый запрос: Kuta ubud — PNL
2026-04-09 00:13:20,318 [DEBUG]: https://api.genius.com:443 "GET /search?q=Kuta+ubud+%E2%80%94+PNL HTTP/1.1" 200 None
2026-04-09 00:13:20,466 [INFO]: Отправлен поисковый запрос: MAMMASTOMALE — MACHETE
2026-04-09 00:13:20,730 [DEBUG]: https://api.genius.com:443 "GET /search?q=MAMMASTOMALE+%E2%80%94+MACHETE HTTP/1.1" 200 None
2026-04-09 00:13:20,788 [INFO]: Отправлен поисковый запрос: Medellín — Madonna
2026-04-09 00:13:21,338 [DEBUG]: https://api.genius.com:443 "GET /search?q=Medell%C3%ADn+%E2%80%94+Madonna HTTP/1.1" 200 None
2026-04-09 00:13:21,548 [INFO]: Отправлен поисковый запрос: Dear my friend — Agust D
2026-04-09 00:13:22,049 [DEBUG]: https://api.genius.com:443 "GET /search?q=Dear+my+friend+%E2%80%94+Agust+D HTTP/1.1" 200 None
2026-04-09 00:13:22,403 [INFO]: Отправлен поисковый запрос: Learn to Fly — Foo Fighters
2026-04-09 00:13:22,915 [DEBUG]: https://api.genius.com:443 "GET /search?q=Learn+to+Fly+%E2%80%94+Foo+Fighters HTTP/1.1" 200 None
2026-04-09 00:13:23,125 [INFO]: Отправлен поисковый запрос: All I Know So Far — P!nk
2026-04-09 00:13:23,734 [DEBUG]: https://api.genius.com:443 "GET /search?q=All+I+Know+So+Far+%E2%80%94+P%21nk HTTP/1.1" 200 None
2026-04-09 00:13:24,462 [INFO]: Отправлен поисковый запрос: Influence — Tove Lo
2026-04-09 00:13:24,937 [DEBUG]: https://api.genius.com:443 "GET /search?q=Influence+%E2%80%94+Tove+Lo HTTP/1.1" 200 None
2026-04-09 00:13:25,264 [INFO]: Отправлен поисковый запрос: Making A Fire — Foo Fighters
2026-04-09 00:13:25,826 [DEBUG]: https://api.genius.com:443 "GET /search?q=Making+A+Fire+%E2%80%94+Foo+Fighters HTTP/1.1" 200 None
2026-04-09 00:13:25,972 [INFO]: Отправлен поисковый запрос: JETSKI — Internet Money
2026-04-09 00:13:26,414 [DEBUG]: https://api.genius.com:443 "GET /search?q=JETSKI+%E2%80%94+Internet+Money HTTP/1.1" 200 None
2026-04-09 00:13:26,443 [INFO]: Отправлен поисковый запрос: DOS MORRITAS — Eslabon Armado
2026-04-09 00:13:26,882 [DEBUG]: https://api.genius.com:443 "GET /search?q=DOS+MORRITAS+%E2%80%94+Eslabon+Armado HTTP/1.1" 200 None
2026-04-09 00:13:26,986 [INFO]: Отправлен поисковый запрос: 3005 — Childish Gambino
2026-04-09 00:13:27,399 [DEBUG]: https://api.genius.com:443 "GET /search?q=3005+%E2%80%94+Childish+Gambino HTTP/1.1" 200 None
2026-04-09 00:13:27,641 [INFO]: Отправлен поисковый запрос: Check — Meek Mill
2026-04-09 00:13:28,152 [DEBUG]: https://api.genius.com:443 "GET /search?q=Check+%E2%80%94+Meek+Mill HTTP/1.1" 200 None
2026-04-09 00:13:28,640 [INFO]: Отправлен поисковый запрос: Take Yourself Home — Troye Sivan
2026-04-09 00:13:29,055 [DEBUG]: https://api.genius.com:443 "GET /search?q=Take+Yourself+Home+%E2%80%94+Troye+Sivan HTTP/1.1" 200 None
2026-04-09 00:13:29,637 [INFO]: Отправлен поисковый запрос: FYTB (FEAT. JOONY) — Brent Faiyaz
2026-04-09 00:13:30,124 [DEBUG]: https://api.genius.com:443 "GET /search?q=FYTB+%28FEAT.+JOONY%29+%E2%80%94+Brent+Faiyaz HTTP/1.1" 200 None
2026-04-09 00:13:30,384 [INFO]: Отправлен поисковый запрос: Interlude : Set me free — Agust D
2026-04-09 00:13:30,972 [DEBUG]: https://api.genius.com:443 "GET /search?q=Interlude+%3A+Set+me+free+%E2%80%94+Agust+D HTTP/1.1" 200 None
2026-04-09 00:13:31,077 [INFO]: Отправлен поисковый запрос: Disaster — Conan Gray
2026-04-09 00:13:31,599 [DEBUG]: https://api.genius.com:443 "GET /search?q=Disaster+%E2%80%94+Conan+Gray HTTP/1.1" 200 None
2026-04-09 00:13:31,688 [INFO]: Отправлен поисковый запрос: On Track — Tame Impala
2026-04-09 00:13:32,228 [DEBUG]: https://api.genius.com:443 "GET /search?q=On+Track+%E2%80%94+Tame+Impala HTTP/1.1" 200 None
2026-04-09 00:13:33,807 [INFO]: Отправлен поисковый запрос: BULERÍAS — ROSALÍA
2026-04-09 00:13:34,299 [DEBUG]: https://api.genius.com:443 "GET /search?q=BULER%C3%8DAS+%E2%80%94+ROSAL%C3%8DA HTTP/1.1" 200 None
2026-04-09 00:13:35,995 [INFO]: Отправлен поисковый запрос: kiss kiss — mgk
2026-04-09 00:13:36,672 [DEBUG]: https://api.genius.com:443 "GET /search?q=kiss+kiss+%E2%80%94+mgk HTTP/1.1" 200 None
2026-04-09 00:13:36,733 [INFO]: Отправлен поисковый запрос: Poquito — Anitta
2026-04-09 00:13:37,242 [DEBUG]: https://api.genius.com:443 "GET /search?q=Poquito+%E2%80%94+Anitta HTTP/1.1" 200 None
2026-04-09 00:13:37,414 [INFO]: Отправлен поисковый запрос: BOMBÓN — Daddy Yankee
2026-04-09 00:13:37,929 [DEBUG]: https://api.genius.com:443 "GET /search?q=BOMB%C3%93N+%E2%80%94+Daddy+Yankee HTTP/1.1" 200 None
2026-04-09 00:13:38,101 [INFO]: Отправлен поисковый запрос: SUPER BOARD — Stray Kids
2026-04-09 00:13:38,651 [DEBUG]: https://api.genius.com:443 "GET /search?q=SUPER+BOARD+%E2%80%94+Stray+Kids HTTP/1.1" 200 None
2026-04-09 00:13:39,364 [INFO]: Отправлен поисковый запрос: Poison — Aaliyah
2026-04-09 00:13:40,088 [DEBUG]: https://api.genius.com:443 "GET /search?q=Poison+%E2%80%94+Aaliyah HTTP/1.1" 200 None
2026-04-09 00:13:40,293 [INFO]: Отправлен поисковый запрос: Les étoiles vagabondes — Nekfeu
2026-04-09 00:13:40,712 [DEBUG]: https://api.genius.com:443 "GET /search?q=Les+%C3%A9toiles+vagabondes+%E2%80%94+Nekfeu HTTP/1.1" 200 None
2026-04-09 00:13:40,985 [INFO]: Отправлен поисковый запрос: Losin Control — Russ
2026-04-09 00:13:41,555 [DEBUG]: https://api.genius.com:443 "GET /search?q=Losin+Control+%E2%80%94+Russ HTTP/1.1" 200 None
2026-04-09 00:13:43,165 [INFO]: Отправлен поисковый запрос: Somo o No Somos — Anuel AA
2026-04-09 00:13:43,681 [DEBUG]: https://api.genius.com:443 "GET /search?q=Somo+o+No+Somos+%E2%80%94+Anuel+AA HTTP/1.1" 200 None
2026-04-09 00:13:43,715 [INFO]: Отправлен поисковый запрос: Cap — KSI
2026-04-09 00:13:44,318 [DEBUG]: https://api.genius.com:443 "GET /search?q=Cap+%E2%80%94+KSI HTTP/1.1" 200 None
2026-04-09 00:13:44,524 [INFO]: Отправлен поисковый запрос: One Of My — Future
2026-04-09 00:13:45,131 [DEBUG]: https://api.genius.com:443 "GET /search?q=One+Of+My+%E2%80%94+Future HTTP/1.1" 200 None
2026-04-09 00:13:45,396 [INFO]: Отправлен поисковый запрос: The Tradition — Halsey
2026-04-09 00:13:45,891 [DEBUG]: https://api.genius.com:443 "GET /search?q=The+Tradition+%E2%80%94+Halsey HTTP/1.1" 200 None
2026-04-09 00:13:46,036 [INFO]: Отправлен поисковый запрос: Amazing Grace — Andrew Andraos
2026-04-09 00:13:46,616 [DEBUG]: https://api.genius.com:443 "GET /search?q=Amazing+Grace+%E2%80%94+Andrew+Andraos HTTP/1.1" 200 None
2026-04-09 00:13:46,674 [INFO]: Отправлен поисковый запрос: Inhale — Bryson Tiller
2026-04-09 00:13:47,321 [DEBUG]: https://api.genius.com:443 "GET /search?q=Inhale+%E2%80%94+Bryson+Tiller HTTP/1.1" 200 None
2026-04-09 00:13:47,357 [INFO]: Отправлен поисковый запрос: Springfield — Tungevaag
2026-04-09 00:13:47,609 [DEBUG]: https://api.genius.com:443 "GET /search?q=Springfield+%E2%80%94+Tungevaag HTTP/1.1" 200 None
2026-04-09 00:13:47,652 [INFO]: Отправлен поисковый запрос: PEPPERMINT — Luciano
2026-04-09 00:13:48,141 [DEBUG]: https://api.genius.com:443 "GET /search?q=PEPPERMINT+%E2%80%94+Luciano HTTP/1.1" 200 None
2026-04-09 00:13:48,173 [INFO]: Отправлен поисковый запрос: Patient — Charlie Puth
2026-04-09 00:13:48,626 [DEBUG]: https://api.genius.com:443 "GET /search?q=Patient+%E2%80%94+Charlie+Puth HTTP/1.1" 200 None
2026-04-09 00:13:48,931 [INFO]: Использован кэш для searches с идентификатором Forever — Lil Baby за 2026-04-08T23:06:59.813772
2026-04-09 00:13:48,955 [INFO]: Отправлен поисковый запрос: Sabe — Nicki Nicole
2026-04-09 00:13:49,468 [DEBUG]: https://api.genius.com:443 "GET /search?q=Sabe+%E2%80%94+Nicki+Nicole HTTP/1.1" 200 None
2026-04-09 00:13:49,583 [INFO]: Отправлен поисковый запрос: LOW LIFE — Ufo361
2026-04-09 00:13:50,136 [DEBUG]: https://api.genius.com:443 "GET /search?q=LOW+LIFE+%E2%80%94+Ufo361 HTTP/1.1" 200 None
2026-04-09 00:13:50,256 [INFO]: Отправлен поисковый запрос: One — Lewis Capaldi
2026-04-09 00:13:50,761 [DEBUG]: https://api.genius.com:443 "GET /search?q=One+%E2%80%94+Lewis+Capaldi HTTP/1.1" 200 None
2026-04-09 00:13:50,987 [INFO]: Отправлен поисковый запрос: Zooted Freestyle — Polo G
2026-04-09 00:13:51,611 [DEBUG]: https://api.genius.com:443 "GET /search?q=Zooted+Freestyle+%E2%80%94+Polo+G HTTP/1.1" 200 None
2026-04-09 00:13:51,814 [INFO]: Отправлен поисковый запрос: Losses — Polo G
2026-04-09 00:13:52,295 [DEBUG]: https://api.genius.com:443 "GET /search?q=Losses+%E2%80%94+Polo+G HTTP/1.1" 200 None
2026-04-09 00:13:52,371 [INFO]: Отправлен поисковый запрос: La Boda Del Huitlacoche - Live — Carín León
2026-04-09 00:13:52,591 [DEBUG]: https://api.genius.com:443 "GET /search?q=La+Boda+Del+Huitlacoche+-+Live+%E2%80%94+Car%C3%ADn+Le%C3%B3n HTTP/1.1" 200 46
2026-04-09 00:13:52,619 [INFO]: Отправлен поисковый запрос: Funeral — Lil Wayne
2026-04-09 00:13:53,093 [DEBUG]: https://api.genius.com:443 "GET /search?q=Funeral+%E2%80%94+Lil+Wayne HTTP/1.1" 200 None
2026-04-09 00:13:53,134 [INFO]: Отправлен поисковый запрос: Genocidal Humanoidz — System Of A Down
2026-04-09 00:13:53,666 [DEBUG]: https://api.genius.com:443 "GET /search?q=Genocidal+Humanoidz+%E2%80%94+System+Of+A+Down HTTP/1.1" 200 None
2026-04-09 00:13:53,689 [INFO]: Отправлен поисковый запрос: fake love don't last — mgk
2026-04-09 00:13:54,240 [DEBUG]: https://api.genius.com:443 "GET /search?q=fake+love+don%27t+last+%E2%80%94+mgk HTTP/1.1" 200 None
2026-04-09 00:13:55,466 [INFO]: Отправлен поисковый запрос: Now That We’re Dead — Metallica
2026-04-09 00:13:56,067 [DEBUG]: https://api.genius.com:443 "GET /search?q=Now+That+We%E2%80%99re+Dead+%E2%80%94+Metallica HTTP/1.1" 200 None
2026-04-09 00:13:56,717 [INFO]: Отправлен поисковый запрос: RER D — Ninho
2026-04-09 00:13:57,301 [DEBUG]: https://api.genius.com:443 "GET /search?q=RER+D+%E2%80%94+Ninho HTTP/1.1" 200 None
2026-04-09 00:14:00,071 [INFO]: Отправлен поисковый запрос: Everything Goes On — Porter Robinson
2026-04-09 00:14:00,967 [DEBUG]: https://api.genius.com:443 "GET /search?q=Everything+Goes+On+%E2%80%94+Porter+Robinson HTTP/1.1" 200 None
2026-04-09 00:14:03,363 [INFO]: Отправлен поисковый запрос: Sei Lá — Juliette
2026-04-09 00:14:03,946 [DEBUG]: https://api.genius.com:443 "GET /search?q=Sei+L%C3%A1+%E2%80%94+Juliette HTTP/1.1" 200 None
2026-04-09 00:14:04,165 [INFO]: Отправлен поисковый запрос: Prima di ogni cosa — Fedez

In [7]:
data = {
    'artist_names': song['artist_names'],
    'title': song['title'],
    'album': song['album']['name'],
    'release_date': song['release_date'],
    'language': song['language'],
    'pageviews': song['stats']['pageviews'],
    'feat_artist_count': len(song['featured_artists']),
    'translate_count': len(song['translation_songs']),
    'third_platform_count': len(song['media']),
    'has_sample': len(song['song_relationships'][0]['songs']) > 0,
    'is_cover': len(song['song_relationships'][4]['songs']) > 0,
    'is_remix': len(song['song_relationships'][6]['songs']) > 0,
    'is_translation': len(song['song_relationships'][-2]['songs']) > 0,
    'image_url': song['header_image_url'],
    'primary_color': song['song_art_primary_color'],
    'secondary_color': song['song_art_secondary_color'],
    'text_color': song['song_art_text_color'],
    'annotation_count': song['annotation_count'],
    'song_description': get_description(song),
    'artist_description': get_description(artist),
    'artist_song_count': len(songs),
    'annotations': annotations,
    'youtube_url': get_youtube_url(song),
}

NameError: name 'song' is not defined