In [1]:
import os
import sys
import pandas as pd

sys.path.append(os.path.abspath('../scripts'))

from kworb import Kworb
from genius import Genius

In [2]:
kworb = Kworb()
df = kworb.spotify_daily_chart_totals('2026-04-08')
df

2026-04-08 18:11:25,216 [INFO]: Данных за 2026-04-08 нет. Загрузка за 2026-04-08...
2026-04-08 18:11:25,225 [DEBUG]: Starting new HTTPS connection (1): kworb.net:443
2026-04-08 18:11:26,516 [DEBUG]: https://kworb.net:443 "GET /spotify/country/global_daily_totals.html HTTP/1.1" 200 3273525
2026-04-08 18:11:28,402 [INFO]: Очистка данных...
2026-04-08 18:11:28,442 [INFO]: Данные за 2026-04-08 успешно сохранены

,date,artist_name,track_title,days_on_chart,top_10_days,peak_position,peak_occurrence,peak_streams,total_streams
rank,,,,,,,,,
1,2026-04-08,The Weeknd,Blinding Lights,2317,446,1,82,"8,453,567","5,268,588,903"
2,2026-04-08,Ed Sheeran,Shape of You,2831,237,1,98,"9,878,194","4,248,356,513"
3,2026-04-08,Harry Styles,As It Was,1417,426,1,81,"16,103,849","4,227,606,484"
4,2026-04-08,Lewis Capaldi,Someone You Loved,2388,107,4,<NA>,"3,974,554","3,902,396,693"
5,2026-04-08,The Neighbourhood,Sweater Weather,2136,,12,<NA>,"3,342,205","3,883,463,849"
...,...,...,...,...,...,...,...,...,...
11746,2026-04-08,Wisin,Adrenalina,1,,188,<NA>,"124,862","124,862"
11747,2026-04-08,Iggy Azalea,Work,1,,196,<NA>,"120,954","120,954"
11748,2026-04-08,Orup,Främling,1,,199,<NA>,"120,760","120,760"
11749,2026-04-08,Ed Sheeran,Nina,1,,199,<NA>,"120,515","120,515"
11750,2026-04-08,Take That,These Days,1,,198,<NA>,"115,382","115,382"

In [3]:
kworb = Kworb()
df = kworb.spotify_daily_chart_totals('2026-04-08')
df

2026-04-08 18:11:31,379 [INFO]: Данные за 2026-04-08 число получены из кэша

,date,artist_name,track_title,days_on_chart,top_10_days,peak_position,peak_occurrence,peak_streams,total_streams
rank,,,,,,,,,
1,2026-04-08,The Weeknd,Blinding Lights,2317,446,1,82.0,"8,453,567","5,268,588,903"
2,2026-04-08,Ed Sheeran,Shape of You,2831,237,1,98.0,"9,878,194","4,248,356,513"
3,2026-04-08,Harry Styles,As It Was,1417,426,1,81.0,"16,103,849","4,227,606,484"
4,2026-04-08,Lewis Capaldi,Someone You Loved,2388,107,4,NaN,"3,974,554","3,902,396,693"
5,2026-04-08,The Neighbourhood,Sweater Weather,2136,,12,NaN,"3,342,205","3,883,463,849"
...,...,...,...,...,...,...,...,...,...
11746,2026-04-08,Wisin,Adrenalina,1,,188,NaN,"124,862","124,862"
11747,2026-04-08,Iggy Azalea,Work,1,,196,NaN,"120,954","120,954"
11748,2026-04-08,Orup,Främling,1,,199,NaN,"120,760","120,760"
11749,2026-04-08,Ed Sheeran,Nina,1,,199,NaN,"120,515","120,515"
11750,2026-04-08,Take That,These Days,1,,198,NaN,"115,382","115,382"

In [5]:
genius = Genius()
genius.search('Blinding Lights The Weeknd')
genius.song(5049949)
genius.artist(2358)
genius.artist_songs(2358)
genius.referents(5049949)
...

2026-04-08 18:12:45,944 [DEBUG]: Starting new HTTPS connection (1): api.genius.com:443
2026-04-08 18:12:48,142 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=1 HTTP/1.1" 200 None
2026-04-08 18:12:49,615 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=2 HTTP/1.1" 200 None
2026-04-08 18:12:51,342 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=3 HTTP/1.1" 200 None
2026-04-08 18:12:53,908 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=4 HTTP/1.1" 200 None
2026-04-08 18:12:55,354 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=5 HTTP/1.1" 200 None
2026-04-08 18:12:57,096 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=6 HTTP/1.1" 200 None
2026-04-08 18:13:01,017 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=7 HTTP/1.1" 200 None
2026-04-08 18:13:02,821 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=8 HTTP/1.1" 200 None
2026-04-08 18:13:04,151 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=9 HTTP/1.1" 200 None
2026-04-08 18:13:06,175 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=10 HTTP/1.1" 200 None
2026-04-08 18:13:10,225 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=11 HTTP/1.1" 200 None
2026-04-08 18:13:11,562 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=12 HTTP/1.1" 200 None
2026-04-08 18:13:13,002 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=13 HTTP/1.1" 200 None
2026-04-08 18:13:14,787 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=14 HTTP/1.1" 200 None
2026-04-08 18:13:16,541 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=15 HTTP/1.1" 200 None
2026-04-08 18:13:17,825 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=16 HTTP/1.1" 200 None
2026-04-08 18:13:18,968 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=17 HTTP/1.1" 200 None
2026-04-08 18:13:20,377 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=18 HTTP/1.1" 200 None
2026-04-08 18:13:21,753 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=19 HTTP/1.1" 200 None
2026-04-08 18:13:23,082 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=20 HTTP/1.1" 200 None
2026-04-08 18:13:24,316 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=21 HTTP/1.1" 200 None
2026-04-08 18:13:26,935 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=22 HTTP/1.1" 200 None
2026-04-08 18:13:27,817 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=23 HTTP/1.1" 200 None
2026-04-08 18:13:28,189 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=24 HTTP/1.1" 200 None
2026-04-08 18:13:28,410 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=25 HTTP/1.1" 200 None
2026-04-08 18:13:28,826 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=26 HTTP/1.1" 200 None
2026-04-08 18:13:29,062 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=27 HTTP/1.1" 200 None
2026-04-08 18:13:29,289 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=28 HTTP/1.1" 200 None
2026-04-08 18:13:29,574 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=29 HTTP/1.1" 200 None
2026-04-08 18:13:29,825 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=30 HTTP/1.1" 200 None
2026-04-08 18:13:30,081 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=31 HTTP/1.1" 200 None
2026-04-08 18:13:30,308 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=32 HTTP/1.1" 200 None
2026-04-08 18:13:31,651 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=33 HTTP/1.1" 200 None
2026-04-08 18:13:31,985 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=34 HTTP/1.1" 200 None
2026-04-08 18:13:33,279 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=35 HTTP/1.1" 200 None
2026-04-08 18:13:33,509 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=36 HTTP/1.1" 200 None
2026-04-08 18:13:33,755 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=37 HTTP/1.1" 200 None
2026-04-08 18:13:34,015 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=38 HTTP/1.1" 200 None
2026-04-08 18:13:34,276 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=39 HTTP/1.1" 200 None
2026-04-08 18:13:34,519 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=40 HTTP/1.1" 200 None
2026-04-08 18:13:35,014 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=41 HTTP/1.1" 200 None
2026-04-08 18:13:35,426 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=42 HTTP/1.1" 200 None
2026-04-08 18:13:35,696 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=43 HTTP/1.1" 200 None
2026-04-08 18:13:36,002 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=44 HTTP/1.1" 200 None
2026-04-08 18:13:36,376 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=45 HTTP/1.1" 200 None
2026-04-08 18:13:36,628 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=46 HTTP/1.1" 200 None
2026-04-08 18:13:36,901 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=47 HTTP/1.1" 200 None
2026-04-08 18:13:37,128 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=48 HTTP/1.1" 200 None
2026-04-08 18:13:37,421 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=49 HTTP/1.1" 200 None
2026-04-08 18:13:37,741 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=50 HTTP/1.1" 200 None
2026-04-08 18:13:37,990 [DEBUG]: https://api.genius.com:443 "GET /artists/2358/songs?sort=popularity&per_page=50&page=51 HTTP/1.1" 200 None
2026-04-08 18:13:38,619 [DEBUG]: https://api.genius.com:443 "GET /referents?song_id=5049949&text_format=plain&per_page=50&page=1 HTTP/1.1" 200 None
2026-04-08 18:13:38,996 [DEBUG]: https://api.genius.com:443 "GET /referents?song_id=5049949&text_format=plain&per_page=50&page=2 HTTP/1.1" 200 None

Ellipsis

In [6]:
genius = Genius()
genius.search('Blinding Lights The Weeknd')
genius.song(5049949)
genius.artist(2358)
genius.artist_songs(2358)
genius.referents(5049949)
...

Ellipsis

In [ ]:
data = {
    'artist_names': song['artist_names'],
    'title': song['title'],
    'album': song['album']['name'],
    'release_date': song['release_date'],
    'language': song['language'],
    'pageviews': song['stats']['pageviews'],
    'feat_artist_count': len(song['featured_artists']),
    'translate_count': len(song['translation_songs']),
    'third_platform_count': len(song['media']),
    'has_sample': len(song['song_relationships'][0]['songs']) > 0,
    'is_cover': len(song['song_relationships'][4]['songs']) > 0,
    'is_remix': len(song['song_relationships'][6]['songs']) > 0,
    'is_translation': len(song['song_relationships'][-2]['songs']) > 0,
    'image_url': song['header_image_url'],
    'primary_color': song['song_art_primary_color'],
    'secondary_color': song['song_art_secondary_color'],
    'text_color': song['song_art_text_color'],
    'annotation_count': song['annotation_count'],
    'song_description': get_description(song),
    'artist_description': get_description(artist),
    'artist_song_count': len(songs),
    'annotations': annotations,
    'youtube_url': get_youtube_url(song),
}